### ISSUE TITLE
`tensor` having divide by zero issue on Go tip

### ISSUE THREAD

**Issue by chewxy** [chewxy/gorgonia#107]
On go tip
```
=== RUN   TestScaleInvBasicProperties
--- FAIL: TestScaleInvBasicProperties (0.03s)
panic: runtime error: integer divide by zero [recovered]
	panic: runtime error: integer divide by zero
goroutine 29 [running]:
testing.tRunner.func1(0xc42007a0d0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:639 +0x253
panic(0xc78740, 0x11abe60)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:489 +0x25b
github.com/chewxy/gorgonia/tensor.scaleinvU8(0xc420160c00, 0x32, 0x32, 0x0, 0x18, 0xc41e00)
	github.com/chewxy/gorgonia/tensor/_test/_obj_test/genericArith.go:3917 +0x1ff
github.com/chewxy/gorgonia/tensor.(*Dense).scaleinv(0xc4201b3aa0, 0xc4a900, 0x1133820, 0x0, 0x0)
	github.com/chewxy/gorgonia/tensor/_test/_obj_test/dense_arith.go:15382 +0x17c4
github.com/chewxy/gorgonia/tensor.(*Dense).ScaleInv(0xc4201b39e0, 0xc4a900, 0x1133820, 0x0, 0x0, 0x0, 0x20, 0xc4204d1020, 0xc4202a5790)
	github.com/chewxy/gorgonia/tensor/_test/_obj_test/dense_arith.go:15161 +0x25f
github.com/chewxy/gorgonia/tensor.TestScaleInvBasicProperties.func21(0xc42038f410, 0xc42038f418, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chewxy/gorgonia/tensor/dense_arith_test.go:17062 +0x92
reflect.Value.call(0xc71380, 0xc4201d22b0, 0x13, 0xd0d430, 0x4, 0xc4201b6050, 0x3, 0x3, 0x4abea4, 0x81, ...)
	/home/travis/.gimme/versions/go/src/reflect/value.go:434 +0xb5f
reflect.Value.Call(0xc71380, 0xc4201d22b0, 0x13, 0xc4201b6050, 0x3, 0x3, 0xc420430930, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/reflect/value.go:302 +0xa4
testing/quick.Check(0xc71380, 0xc4201d22b0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/testing/quick/quick.go:288 +0x28d
github.com/chewxy/gorgonia/tensor.TestScaleInvBasicProperties(0xc42007a0d0)
	/home/travis/gopath/src/github.com/chewxy/gorgonia/tensor/dense_arith_test.go:17077 +0xf13
testing.tRunner(0xc42007a0d0, 0xd33510)
	/home/travis/.gimme/versions/go/src/testing/testing.go:674 +0x98
created by testing.(*T).Run
	/home/travis/.gimme/versions/go/src/testing/testing.go:716 +0x2d5
exit status 2
FAIL	github.com/chewxy/gorgonia/tensor	0.990s
```

**Comment by ctava** [comment]
$ go test
PASS
ok      github.com/chewxy/gorgonia/tensor       2.886s

is this issue still actual?

**Comment by chewxy** [comment]
Yes. Cause was this: https://github.com/golang/go/issues/19808
