### ISSUE TITLE
missing testdata files for provided examples

### ISSUE THREAD

**Issue by omac777** [chewxy/gorgonia#110]
I'm on archlinux:
4.10.11-1-ARCH #1 SMP PREEMPT Tue Apr 18 08:39:42 CEST 2017 x86_64 GNU/Linux

Originally when building it, I was getting:
```
 $ go build -tags='cuda'
  github.com/gonum/blas/cgo
/tmp/go-build150810894/github.com/gonum/blas/cgo/_obj/blas.cgo2.o: In function `_cgo_42fd92bc8ecb_Cfunc_cblas_cgbmv':
```

I then git cloned and installed openblas, all the available blas packages including the openblas package available through aur were naming the output to libblas* NOT libopenblas as gorgonia expects them to be.
```
  $ ls -lht /usr/local/lib/
lrwxrwxrwx 1 root root   35 Apr 20 15:32 libopenblas.so -> libopenblas_nehalemp-r0.2.20.dev.so
lrwxrwxrwx 1 root root   35 Apr 20 15:32 libopenblas.so.0 -> libopenblas_nehalemp-r0.2.20.dev.so
lrwxrwxrwx 1 root root   34 Apr 20 15:32 libopenblas.a -> libopenblas_nehalemp-r0.2.20.dev.a
-rwxr-xr-x 1 root root  14M Apr 20 15:31 libopenblas_nehalemp-r0.2.20.dev.so
-rw-r--r-- 1 root root  27M Apr 20 15:30 libopenblas_nehalemp-r0.2.20.dev.a
```

```
cd ~/Code/go/src/github.com/chewxy/gorgonia/blase
  $ CGO_CFLAGS="-I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib -lopenblas" go build -tags='cuda'

  $ LD_LIBRARY_PATH=/usr/local/lib CGO_CFLAGS="-I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib -lopenblas" go test
PASS
ok  	github.com/chewxy/gorgonia/blase	0.010s

  $ LD_LIBRARY_PATH=/usr/local/lib CGO_CFLAGS="-I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib -lopenblas" go install


cd "~/Code/go/src/github.com/chewxy/gorgonia/examples/stacked autoencoder"
 $ LD_LIBRARY_PATH=/usr/local/lib CGO_CFLAGS="-I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib -lopenblas" go build
```

Ok so the "stacked autoencoder" example builds, but two issues arose:

## There were no input files to use. ##
I would have also liked some test data files for charRNN,  cuda and the logisticregression examples.
2017/04/20 15:53:38 path: "train-labels.idx1-ubyte" err: open train-labels.idx1-ubyte: no such file or directory
I found some here: http://yann.lecun.com/exdb/mnist/
but they needed to be renamed a bit.  

```
mv t10k-labels-idx1-ubyte t10k-labels.idx1-ubyte
mv t10k-images-idx3-ubyte t10k-images.idx3-ubyte
mv train-labels-idx1-ubyte train-labels.idx1-ubyte
mv train-images-idx3-ubyte train-images.idx3-ubyte
```
there are many cli switches available when invoking the "stacked autoencoder"

## the defaults even with the input file present, gave me core dumps. ##
```
LD_LIBRARY_PATH=/usr/local/lib ./stacked\ autoencoder -bs 1 -cpuprofile "mycpuprofile.out" -dataset "dev" -ft 40 -memprofile "mymemprofile.out" -pt 16 -save "mysaveas" -viz 0
LD_LIBRARY_PATH=/usr/local/lib ./stacked\ autoencoder -bs 1 -cpuprofile "mycpuprofile.out" -dataset "dev" -ft 40 -memprofile "mymemprofile.out" -pt 16 -save "mysaveas" -viz 1
LD_LIBRARY_PATH=/usr/local/lib ./stacked\ autoencoder -bs 5 -cpuprofile "mycpuprofile.out" -dataset "dev" -ft 40 -memprofile "mymemprofile.out" -pt 16 -save "mysaveas" -viz 1
LD_LIBRARY_PATH=/usr/local/lib ./stacked\ autoencoder --help
LD_LIBRARY_PATH=/usr/local/lib ./stacked\ autoencoder -bs 5 -cpuprofile "mycpuprofile.out" -dataset "train" -ft 40 -memprofile "mymemprofile.out" -pt 16 -save "mysaveas" -viz 1
LD_LIBRARY_PATH=/usr/local/lib ./stacked\ autoencoder -bs 5 -cpuprofile mycpuprofile.out -dataset dev -ft 40 -memprofile mymemprofile.out -pt 16 -save mysaveas -viz 1
LD_LIBRARY_PATH=/usr/local/lib ./stacked\ autoencoder 

 $ LD_LIBRARY_PATH=/usr/local/lib  ./stacked\ autoencoder
Stacked Denoising AutoEncoder

 ==============================
	Train on: dev
	Training Size: 100
	Hidden Sizes: [1000 1000 1000]
	Corruptions: [0.1 0.2 0.3]
	Batch Size: 1
	Pretraining Epoch: 16
	Finetuning Epoch: 40
	BLAS used: Blase
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8472ac]

goroutine 1 [running]:
github.com/chewxy/gorgonia.(*interval).merge(0xc42010a2a0, 0x0)
	/home/dma2/Code/go/src/github.com/chewxy/gorgonia/regalloc.go:140 +0x2c
github.com/chewxy/gorgonia.(*regalloc).alloc(0xc4200a37f0, 0xc4200d4600, 0x2d, 0x2d)
	/home/dma2/Code/go/src/github.com/chewxy/gorgonia/regalloc.go:368 +0x46c
github.com/chewxy/gorgonia.CompileFunction(0xc42008e090, 0xc42000e0e8, 0x1, 0x1, 0xc4200ab5a0, 0x3, 0x4, 0x0, 0x0, 0x0, ...)
	/home/dma2/Code/go/src/github.com/chewxy/gorgonia/compile.go:76 +0x454
main.(*StackedDA).Pretrain(0xc42008e120, 0xdf3de0, 0xc420018180, 0x0, 0x0, 0x3)
	/home/dma2/Code/go/src/github.com/chewxy/gorgonia/examples/stacked autoencoder/stackedDA.go:101 +0x219
main.main()
	/home/dma2/Code/go/src/github.com/chewxy/gorgonia/examples/stacked autoencoder/main.go:169 +0x562
```

That's all I can provide for now.

**Comment by chewxy** [comment]
Formatted your issue 

**Regarding issue 1** : you have indeed found the correct input files. The reason why they are differently name depends on what machine you unzip the files from. On MacOS machines, you'll unzip to the name I have above. 

**Regarding Issue 2** : the StackedDA example does not work for CUDA right now (even on the `cuda2` branch). The upcoming #93 pull request WILL fix this problem. This library is going thru a mild refactoring to better handle CUDA and OpenCL stuff in the future.
