### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xiajohnnyxia** [chewxy/gorgonia#160]
hello chewxy, i am learning your framework.When i was running your example in `/src/github.com/chewxy/gorgonia/examples/stacked autoencoder` . 
There are many nil pointers error in it.
And i use the data at [http://yann.lecun.com/exdb/mnist/](url).What's wrong with it?

```

Stacked Denoising AutoEncoder
==============================
	Train on: dev
	Training Size: 100
	Hidden Sizes: [1000 1000 1000]
	Corruptions: [0.1 0.2 0.3]
	Batch Size: 1
	Pretraining Epoch: 16
	Finetuning Epoch: 40
	BLAS used: Blase
2017/09/22 23:17:58 [x :: Vector float64 w_0 :: Matrix float64 b_0 :: Vector float64 Aᵀ × b(%1, %0) :: Vector float64 + false(%3, %2) :: Vector float64 sigmoid(%4) :: Vector float64 Aᵀ{1, 0}(%1) :: Matrix float64 %!s(<nil>)() :: Vector float64 2(1, 0.1) - ()() :: float64 w_1 :: Matrix float64 b_1 :: Vector float64 Aᵀ × b(%9, %5) :: Vector float64 + false(%b, %a) :: Vector float64 sigmoid(%c) :: Vector float64 Aᵀ{1, 0}(%9) :: Matrix float64 b_2 :: Vector float64 w_2 :: Matrix float64 Aᵀ × b(%10, %d) :: Vector float64 + false(%11, %f) :: Vector float64 sigmoid(%12) :: Vector float64 %!s(<nil>)() :: Vector float64 Softmax_w :: Matrix float64 Softmax_b :: Vector float64 ⊙ false(%8, %0) :: Vector float64 Aᵀ × b(%1, %17) :: Vector float64 + false(%18, %2) :: Vector float64 sigmoid(%19) :: Vector float64 Aᵀ × b(%6, %1a) :: Vector float64 + false(%1b, %7) :: Vector float64 sigmoid(%1c) :: Vector float64 neg(%1c) :: Vector float64 softplus(%1e) :: Vector float64 neg(%1f) :: Vector float64 1 :: float64{1} - false(%21, %0) :: Vector float64 ⊙ false(%0, %20) :: Vector float64 neg(%1d) :: Vector float64 softplus(%1c) :: Vector float64 neg(%26) :: Vector float64 ⊙ false(%22, %27) :: Vector float64 + false(%24, %28) :: Vector float64 neg(%29) :: Vector float64 Σ[0](%2a) :: float64 SizeOf=784(%2a) :: float64 ÷ false(%2b, %2c) :: float64 read ÷ false(%2b, %2c) :: float64 into 0xc42013ccc0 :: <nil> ÷ false(%21, %2c) :: float64 ÷ false(%2d, %2c) :: float64 neg(%30) :: float64 ⊙ false(%31, %21) :: float64 Repeat[0](%2f, %2c) :: Vector float64 neg(%33) :: Vector float64 ⊙ false(%27, %34) :: Vector float64 ⊙ false(%22, %34) :: Vector float64 neg(%36) :: Vector float64 ⊙ false(%1d, %37) :: Vector float64 ⊙ false(%20, %34) :: Vector float64 ⊙ false(%0, %34) :: Vector float64 neg(%3a) :: Vector float64 sigmoid(%1e) :: Vector float64 ⊙ false(%3c, %3b) :: Vector float64 neg(%3d) :: Vector float64 + false(%38, %3e) :: Vector float64 a ⊗ b(%1a, %3f) :: Matrix float64 A × b(%6, %3f) :: Vector float64 - false(%21, %1a) :: Vector float64 ⊙ false(%1a, %42) :: Vector float64 ⊙ false(%43, %41) :: Vector float64 a ⊗ b(%17, %44) :: Matrix float64 A × b(%1, %44) :: Vector float64 Aᵀ{1, 0}(%40) :: Matrix float64 + false(%45, %47) :: Matrix float64]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8e813c]

goroutine 1 [running]:
github.com/chewxy/gorgonia.(*interval).merge(0xc42014aee0, 0x0)
	/src/github.com/chewxy/gorgonia/regalloc.go:111 +0x2c
github.com/chewxy/gorgonia.(*regalloc).alloc(0xc4201677a8, 0xc42010a600, 0x2d, 0x2d)
	/src/github.com/chewxy/gorgonia/regalloc.go:317 +0x501
github.com/chewxy/gorgonia.CompileFunction(0xc420084090, 0xc42000e0f0, 0x1, 0x1, 0xc420172080, 0x3, 0x4, 0x0, 0x0, 0x0, ...)
	/src/github.com/chewxy/gorgonia/compile.go:88 +0x4cb
main.(*StackedDA).Pretrain(0xc4200841b0, 0xf73c60, 0xc42007c420, 0x0, 0x0, 0x3)
	/src/github.com/chewxy/gorgonia/examples/stacked autoencoder/stackedDA.go:103 +0x30f
main.main()
	/src/github.com/chewxy/gorgonia/examples/stacked autoencoder/main.go:174 +0x562
```

**Comment by chewxy** [comment]
the example is old and stale. In the upcoming release the examples will ALL be updated.

**Comment by chewxy** [comment]
Also you probably shouldn't use Blase anymore. For this version Blase is kinda crappy. New design of Blase coming

**Comment by chewxy** [comment]
I'll dig deeper into this tomorrow morning

**Comment by xiajohnnyxia** [comment]
ok,how can i get your support?Do you have a team i can join?

**Comment by chewxy** [comment]
You're in the right spot (opening the ticket). I also hang out at the gophers slack.

**Comment by xiajohnnyxia** [comment]
How can i associated with that workspace?

**Comment by chewxy** [comment]
send me an email - chewxy [at] gmail.com I'll send you an invite

*Xuanyi Chew*
*@chewxy on Twitter*
*Read:* my blog <http://blog.chewxy.com>
*+61403928398*

**Comment by xiajohnnyxia** [comment]
I run it again just now.A new error appeared.

```
Stacked Denoising AutoEncoder
==============================
	Train on: dev
	Training Size: 100
	Hidden Sizes: [1000 1000 1000]
	Corruptions: [0.1 0.2 0.3]
	Batch Size: 1
	Pretraining Epoch: 16
	Finetuning Epoch: 40
	BLAS used: Blase
2017/09/24 04:57:40 w (784, 1000) da.h.w (1000, 784)
2017/09/24 04:57:41 w (1000, 1000) da.h.w (1000, 1000)
2017/09/24 04:57:41 w (1000, 1000) da.h.w (1000, 1000)
panic: interface conversion: interface {} is float64, not []float64

goroutine 1 [running]:
main.makeTargets(0xf79c60, 0xc45e89e160, 0xc45e89e160, 0xf79c60, 0xc45e89e160)
	/src/github.com/chewxy/gorgonia/examples/stacked autoencoder/main.go:110 +0x2b1
main.main()
	/src/github.com/chewxy/gorgonia/examples/stacked autoencoder/main.go:230 +0xf45
```

```
func makeTargets(targets tensor.Tensor) []int {
	ys := make([]int, targets.Shape()[0])
	ys = ys[:0]
	for i := 0; i < targets.Shape()[0]; i++ {
		ysl, _ := targets.Slice(T.S(i))
		**raw := ysl.Data().([]float64)**
		for i, v := range raw {
			if v == 0.9 {
				ys = append(ys, i)
				break
			}
		}
	}
	return ys
}
```

**Comment by chewxy** [comment]
Yep. When I cherry picked the file I picked the wrong commit for that. My bad. Will fix it later today
